resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.17"

resources:
  - name: spring-boot-service
    type: git
    source:
      uri: git@github.com:robin0695/concourse-ci-cd.git
      branch: master
      icon: github
      private_key: ((git-private-key))

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

  - name: kubectl-res
    type: kubernetes
    source:
      kubeconfig: ((kubeconfig-file-content))

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/concourse_ci/tasks/maven-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/concourse_ci/tasks/maven-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out

  - name: deploy
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [package]
      - put: kubectl-res
        params:
          kubectl: delete -f spring-boot-service/spring-boot-deploy.yaml
      - put: kubectl-res
        params:
          kubectl: apply -f spring-boot-service/spring-boot-deploy.yaml
