---
platform: linux
caches:
- path: $HOME/.m2/repository/
- path: $HOME/.gradle/caches/
- path: $HOME/.gradle/wrapper/
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine


inputs:
  - name: spring-boot-service

run:
  path: "mvn"
  args:
    - -f
    - spring-boot-service/pom.xml
    - clean
    - test
